<?php
namespace Neos\Flow\Persistence\Doctrine\Migrations;

use Doctrine\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs! This block will be used as the migration description if getDescription() is not used.
 */
class Version20180223093624 extends AbstractMigration
{

    /**
     * @return string
     */
    public function getDescription(): string 
    {
        return '';
    }

    /**
     * @param Schema $schema
     * @return void
     */
    public function up(Schema $schema): void 
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on "mysql".');
        
        $this->addSql('ALTER TABLE mindscreen_projectpackages_domain_model_package_join DROP FOREIGN KEY FK_79B259A82F585505');
        $this->addSql('ALTER TABLE mindscreen_projectpackages_domain_model_package_join ADD CONSTRAINT FK_79B259A82F585505 FOREIGN KEY (dependency) REFERENCES mindscreen_projectpackages_domain_model_package (persistence_object_identifier) ON DELETE CASCADE');
    }

    /**
     * @param Schema $schema
     * @return void
     */
    public function down(Schema $schema): void 
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on "mysql".');
        
        $this->addSql('ALTER TABLE mindscreen_projectpackages_domain_model_package_join DROP FOREIGN KEY FK_79B259A82F585505');
        $this->addSql('ALTER TABLE mindscreen_projectpackages_domain_model_package_join ADD CONSTRAINT FK_79B259A82F585505 FOREIGN KEY (dependency) REFERENCES mindscreen_projectpackages_domain_model_package (persistence_object_identifier)');
    }
}