<?php
namespace Neos\Flow\Persistence\Doctrine\Migrations;

use Doctrine\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs! This block will be used as the migration description if getDescription() is not used.
 */
class Version20180223081803 extends AbstractMigration
{

    /**
     * @return string
     */
    public function getDescription(): string 
    {
        return '';
    }

    /**
     * @param Schema $schema
     * @return void
     */
    public function up(Schema $schema): void 
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on "mysql".');
        
        $this->addSql('CREATE TABLE mindscreen_projectpackages_domain_model_package_join (package VARCHAR(40) NOT NULL, dependency VARCHAR(40) NOT NULL, INDEX IDX_79B259A8DE686795 (package), INDEX IDX_79B259A82F585505 (dependency), PRIMARY KEY(package, dependency)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('ALTER TABLE mindscreen_projectpackages_domain_model_package_join ADD CONSTRAINT FK_79B259A8DE686795 FOREIGN KEY (package) REFERENCES mindscreen_projectpackages_domain_model_package (persistence_object_identifier)');
        $this->addSql('ALTER TABLE mindscreen_projectpackages_domain_model_package_join ADD CONSTRAINT FK_79B259A82F585505 FOREIGN KEY (dependency) REFERENCES mindscreen_projectpackages_domain_model_package (persistence_object_identifier)');
        $this->addSql('DROP TABLE mindscreen_projectpackages_domain_model_59dec_dependencies_join');
    }

    /**
     * @param Schema $schema
     * @return void
     */
    public function down(Schema $schema): void 
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on "mysql".');
        
        $this->addSql('CREATE TABLE mindscreen_projectpackages_domain_model_59dec_dependencies_join (projectpackages_package VARCHAR(40) NOT NULL COLLATE utf8_unicode_ci, PRIMARY KEY(projectpackages_package)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('ALTER TABLE mindscreen_projectpackages_domain_model_59dec_dependencies_join ADD CONSTRAINT FK_D31F101B6F8EF12D FOREIGN KEY (projectpackages_package) REFERENCES mindscreen_projectpackages_domain_model_package (persistence_object_identifier)');
        $this->addSql('DROP TABLE mindscreen_projectpackages_domain_model_package_join');
    }
}