Neos:
  Flow:
    mvc:
      routes:
        'Mindscreen.ProjectPackages': true

Mindscreen:
  ProjectPackages:
    icons:
      project:
        composer: resource://Mindscreen.ProjectPackages/Public/Images/Icons/composer.png
        npm: resource://Mindscreen.ProjectPackages/Public/Images/Icons/npm.png
        vagrant: resource://Mindscreen.ProjectPackages/Public/Images/Icons/vagrant.png
        yarn: resource://Mindscreen.ProjectPackages/Public/Images/Icons/yarn.png
#    allowCrossOriginRequests: false
#    clients:
#      myGitlab:
#        type: Mindscreen\ProjectPackages\Strategy\RepositorySource\Gitlab
#        options:
#          url: ''
#          token: ''
